### ISSUE TITLE
โค๊ต

### ISSUE THREAD

**Issue by DEV-F41** [DEV-F41/-#1]
//rotate left
#include <stdio.h>
void printfArray(int[],int);
void rotateLeft(int[],int);
void rotateRight(int[],int);
int main(){
	int n[] = {3,9,1,5,12,25,10};
	int length = sizeof(n)/sizeof(n[0]);
	
	printfArray(n,length);
	rotateLeft(n,length);	
	rotateRight(n,length);	
	return 0;
}
void printfArray(int n[],int l){
	int i;
	for(i=0;i<l;i++){
		
		printf("%d ",n[i]);
	}
	printf("\n");
}
void rotateLeft(int n[],int l){
	int i,temp;
	temp = n[0];
	for(i=1;i<l;i++){
		n[i-1]=n[i];
		printf("%d ",n[i]);
	}
	n[l-1]=temp;
	printf("%d",temp);
	printf("\n");
}
void rotateRight(int n[],int l){
	int i,temp;
	temp = n[l-1];
	for(i=l-1;i>0;i--){
		n[i]=n[i-1];
		printf("%d ",n[i]);
	}
	n[0]=temp;
	printf("%d",temp);
}

**Comment by KOB4k** [comment]
> //rotate left
> #include <stdio.h>
> void printfArray(int[],int);
> void rotateLeft(int[],int);
> void rotateRight(int[],int);
> int main(){
> int n[] = {3,9,1,5,12,25,10};
> int length = sizeof(n)/sizeof(n[0]);
> 
> ```
> printfArray(n,length);
> rotateLeft(n,length);	
> rotateRight(n,length);	
> return 0;
> ```
> }
> void printfArray(int n[],int l){
> int i;
> for(i=0;i<l;i++){
> 
> ```
> 	printf("%d ",n[i]);
> }
> printf("\n");
> ```
> }
> void rotateLeft(int n[],int l){
> int i,temp;
> temp = n[0];
> for(i=1;i<l;i++){
> n[i-1]=n[i];
> printf("%d ",n[i]);
> }
> n[l-1]=temp;
> printf("%d",temp);
> printf("\n");
> }
> void rotateRight(int n[],int l){
> int i,temp;
> temp = n[l-1];
> for(i=l-1;i>0;i--){
> n[i]=n[i-1];
> printf("%d ",n[i]);
> }
> n[0]=temp;
> printf("%d",temp);
> }
